### ISSUE TITLE
Re-purpose repository, decommission or transfer.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp-server#12]
Hi guys!

I am currently pretty satisfied with hydration of pre-rendered HTML to add SEO capabilities to my apps, so I haven't been interested on working on this repo. The last commit by @benjaminj6 was a few months ago and there has been little activity since then, so I'd like to take action in one of the following ways:

1) Decommission the repo.
2) Re-purpose the repo for `@hyperapp/hydrate`.
3) Transfer the repo to anyone who is willing to work on it.

/cc @SkaterDad @andyrj

**Comment by JorgeBucaran** [comment]
I'll transfer the repo to @andyrj in the meantime, if @SkaterDad wants another arrangement and I am sure you will be able to figure something out! 😄

**Comment by andyrj** [comment]
that works for me

**Comment by SkaterDad** [comment]
Works for me, as well.
