### ISSUE TITLE
Readme question

### ISSUE THREAD

**Issue by skiano** [hyperapp/hyperapp-server#14]
I am very excited to see activity on this front :)

thanks @frenzzy!

Small question

The readme says this has been deprecated in favor of:
https://github.com/frenzzy/hyperapp-render

and that is a fork of:
https://github.com/HyperappCommunity/hyperapp-server

Which one is official? I assume the community one. If so should the README link be changed?

**Comment by SkaterDad** [comment]
@skiano This library hasn't been maintained for a while.  `hyperapp-render` is probably the way to go for now.

**Comment by skiano** [comment]
thanks!
